-- AlterEnum: add BANK_STDBANK to WalletProvider
ALTER TABLE `DepositEvent` MODIFY `provider` ENUM('PAYPULSE', 'EASYWALLET', 'PAY2CELL', 'EWALLET', 'BANK_WHK', 'BANK_STDBANK') NOT NULL;
ALTER TABLE `WalletNumber` MODIFY `provider` ENUM('PAYPULSE', 'EASYWALLET', 'PAY2CELL', 'EWALLET', 'BANK_WHK', 'BANK_STDBANK') NOT NULL;
